### ISSUE TITLE
请问你的小猫 锚点，与背面的点击一次就变化的七彩粗线条是用了什么，望告知，感觉很好看！

### ISSUE THREAD

**Issue by SuichenTree** [DIYgod/diygod.me#2]
还有那个aplayer音乐播放器，一直存在在主页中，所以点击链接，使用ajax，加载页面，所以音乐不会断掉，是这样吗？

**Comment by ToBegin** [comment]
今天无意中看B站的BAS弹幕说明，然后一步步找到了作者。访问了作者的主页，瞬间被惊艳到了，立刻研究了一波，冒昧替作者回答一下

1. 小猫锚点是使用的 cursor 的 url，样式在body中可以看到
2. 背景是Vue的作者尤大的个人主页效果，作者也使用id注明了
3. aplayer 也是作者的开源项目，歌曲的话看api的话最终来源网易云（我还收藏了几首歌~）

ps: 个人的技术栈也是Vue，跟着作者的项目学到了很多，哔哩哔哩 (゜-゜)つロ 干杯~-bilibili
