### ISSUE TITLE
关乎图片

### ISSUE THREAD

**Issue by wangkun19930608** [DIYgod/diygod.me#6]
我也在用[GithubPage](https://wangkun19930608.github.io/)，当然，和博主的风格是没法比了，有点好奇博主的图片存储，每次写连接时候，都是需要先把图片存储好，再在文章里面写连接，这样子有点不便携，因此好多我的好写文章都是不带图片的，博主有什么好一些的办法吗？

顺便求下友链。已加。

**Comment by DIYgod** [comment]
我的图片都是放 [source/images](https://github.com/DIYgod/diygod.me/tree/hexo/source/images) 里的...

**Comment by qdchenyixuan** [comment]
我个人也是放在项目里的，还有又拍云免费（要有域名），Chrome插件：新浪微博图床这种（这两种可能都不太稳）

**Comment by wangkun19930608** [comment]
多谢了！

**Comment by wangkun19930608** [comment]
过来求个友链，那个评论系统总是显示的不正常。
昵称：*坤的博客
介绍：分享所感兴趣的所有电脑技术
网址：https://wangkun19930608.github.io
